# Generated by Django 3.1.1 on 2020-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_dept',
            field=models.CharField(choices=[('중등', '중등'), ('고등', '고등')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_file',
            field=models.ImageField(blank=True, upload_to='teacher/'),
        ),
    ]
