# Generated by Django 3.1.1 on 2020-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20201106_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_img',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_pay',
            field=models.IntegerField(choices=[(280000, '중등 : 280,000원'), (350000, '고등 : 350,000원')]),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_term',
            field=models.IntegerField(choices=[(1, '1개월'), (2, '2개월'), (3, '3개월')]),
        ),
    ]
