# Generated by Django 3.1.2 on 2020-11-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20201103_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tbl',
            name='c_code_valid',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
