# Generated by Django 3.1.2 on 2020-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_customer_tbl_c_code_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_pw',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_pw',
            field=models.CharField(max_length=100),
        ),
    ]
