# Generated by Django 3.1.2 on 2020-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20201106_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_class',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_dept',
            field=models.CharField(choices=[('중등', '중등'), ('고등', '고등')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_img',
            field=models.ImageField(null=True, upload_to='lecture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_pay',
            field=models.IntegerField(choices=[(280000, '중등 : 280,000원'), (350000, '고등 : 350,000원')]),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_subject',
            field=models.CharField(choices=[('수학', '수학'), ('영어', '영어')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_term',
            field=models.IntegerField(choices=[(1, '1개월'), (2, '2개월'), (3, '3개월')]),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_file',
            field=models.ImageField(blank=True, upload_to='teacher/'),
        ),
    ]
