# Generated by Django 3.1.2 on 2020-11-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20201110_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_class',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notice_tbl',
            name='notice_target',
            field=models.CharField(choices=[('선생님', '선생님'), ('전체', '전체')], max_length=20),
        ),
    ]
