# Generated by Django 3.1.2 on 2020-11-11 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0007_auto_20201111_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('c_name', models.CharField(max_length=10)),
                ('c_id', models.CharField(max_length=40, unique=True)),
                ('c_pw', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=20)),
                ('c_gender', models.CharField(max_length=10)),
                ('c_join', models.DateField(auto_now_add=True)),
                ('c_birth', models.DateField()),
                ('c_code', models.CharField(max_length=6, null=True)),
                ('c_add', models.CharField(max_length=50, null=True)),
                ('c_school', models.CharField(max_length=50, null=True)),
                ('c_state', models.BooleanField()),
                ('c_out', models.DateField(null=True)),
                ('c_code_valid', models.CharField(max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
