# Generated by Django 3.1.3 on 2020-11-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tbl',
            name='c_code_valid',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterModelTable(
            name='customer_tbl',
            table='customer',
        ),
    ]
