# Generated by Django 3.1.3 on 2020-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=10),
        ),
    ]
