# Generated by Django 3.1.3 on 2020-11-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0002_auto_20201106_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_add',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
