# Generated by Django 3.1.3 on 2020-11-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0003_auto_20201106_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_file',
            field=models.ImageField(blank=True, upload_to='teacher/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_pw',
            field=models.CharField(max_length=100),
        ),
    ]
