# Generated by Django 3.1.3 on 2020-11-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0004_auto_20201110_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_file',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/'),
        ),
    ]
